name: GitHub CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Nucleus
      run: source install.sh
    - name: Test 
      run: |
        set -x -e
        bazel test -c opt $COPT_FLAGS nucleus/...
