name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        set -x -e
        git log --pretty -1
        source install.sh
        bazel test -c opt $COPT_FLAGS nucleus/...
